### ISSUE TITLE
Docker: timeouts?

### ISSUE THREAD

**Issue by xme** [AssuranceMaladieSec/CertStreamMonitor#1]
I'm running the tool in a Docker (standard docker-compose/dockerfile).
I detected regular timeouts to the CertStream service:

```
certstreammonitor    | Error connecting to CertStream - Connection is already closed. - Sleeping for a few seconds and trying again...
certstreammonitor    | Connection established to CertStream! Listening for events...
```

**Comment by ThDamon** [comment]
It seems that sometimes the CertStream WebSocket service send FIN+PSH packet, this generates the 
"Error connecting to CertStream - Connection is already closed. - Sleeping for a few seconds and trying again..." message. The socket reconnect automatically after that.

**Comment by brycampbell** [comment]
Same as @xme I get 

`Connection established to CertStream! Listening for events...`

And  nothing happens, is there a fix for this?

**Comment by cbrocas** [comment]
Hi @xme , due to this code update (https://github.com/AssuranceMaladieSec/CertStreamMonitor/issues/13 ) we operate now our own CertStream server instance (in a docker) based on https://github.com/CaliDog/certstream-server . We have a far better stability of the connections to this engine than to the Calidog Security engine behind Cloudflare.

**Comment by cbrocas** [comment]
The option in the config file to point to your Certificate Transparency Aggregator server is : ACTServer. The format is : 
ACTServer = wss://hostname
(Hostname under a FQDN format).

**Comment by xme** [comment]
Tx for the followup. I just rebuild my new container with the newest code.
