### ISSUE TITLE
Error connecting to CertStream 

### ISSUE THREAD

**Issue by secusoc** [AssuranceMaladieSec/CertStreamMonitor#12]
Hello,

Thanks for your tool.

My conf: 
```
RHEL 7.5 (Maipo)
Python 3.4.9
Launch by: python3 /home/sec/CertStreamMonitor/CertStreamMonitor.py -c /home/sec/CertStreamMonitor/conf/test.conf
```

Since i use it , it works sometimes for 10minutes and then only error for hours:
```
[ERROR:root] 2018-11-01 20:38:35,315 - Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...
[ERROR:root] 2018-11-01 20:40:47,539 - Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...
[ERROR:root] 2018-11-01 20:42:59,891 - Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...
[ERROR:root] 2018-11-01 20:45:12,116 - Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...
[ERROR:root] 2018-11-01 20:47:24,339 - Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...
```

I try with word "en" that match a lot of hostname => But always the same problem.
```
Looking for these strings: en
Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...
Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...
Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...
Error connecting to CertStream - [Errno 110] Connection timed out - Sleeping for a few seconds and trying again...

```

95% of time , i don"t access the stream...
(No problem with proxy because i see connection with certstream.calidog.io )

I kill and reload CertStreamMonitor.py each 25minutes to create a new websocket but same error

If you have an idea
Regards

**Comment by cbrocas** [comment]
Hi!
May you describe your setup more in details please? 
- Docker or plain install
- Server connected directly to the Internet? Use of proxy? What kind?
Thanks

**Comment by soukoye** [comment]
Hi cbrocas,
Sorry for delay
- It's a plain install: unzip CertStreamMonitor and configure my settings
- I'm using a http proxy with "no authentication".
 On proxy logs: All requests are going out to certstream.caligod.io
- No problem with Firewall.
- I try a simple regex.  (ex: test or sport)
sometimes its working (always when i start process) then errors for hours
Regards

**Comment by ThDamon** [comment]
Hi soukoye,

The error message, and more specifically the "_[Errno 110] Connection timed out_" string, is probably an error message emitted by websocket-client package, this package is used by the certstream-python package itself. Since v1.10 the CaliDog's certstream-python package can use an HTTP proxy to connect to the websocket providing CT flows.
Could you try to change line 172 of CertStreamMonitor.py (https://github.com/AssuranceMaladieSec/CertStreamMonitor/blob/master/CertStreamMonitor.py#L172) for `certstream.listen_for_events(print_callback, "wss://certstream.calidog.io", http_proxy_host="proxy_host", http_proxy_port=8080)`
(please adapt your http_proxy_host and http_proxy_port) and tell us if your websocket connection is better.
Thank you.

**Comment by soukoye** [comment]
Hi ThDamon,

Your change resolve my problem.
You can close the case.

Thanks to you and cbrocas for your help and this tools

Regards
(Merci beaucoup)

**Comment by ThDamon** [comment]
You're welcome  :)
